[DO NOT MERGE] Init user api for node sdk 2.1.0
milvus-io/web-content pull request #724
Opened 2022-07-26 12:01 UTC by nameczz

Signed-off-by: nameczz <zizhao.chen@zilliz.com>

2022-07-26 12:19 UTC, shanghaikid requested changes

2022-07-27 02:58 UTC, YiyunNi commented on API_Reference/milvus-sdk-node/v2.1.0/Usr/listUsers.md
> +| --------- | ----------- | ---- | -------- |
Can we delete this parameters table and just say there is none?

2022-07-27 03:08 UTC, nameczz commented on API_Reference/milvus-sdk-node/v2.1.0/Usr/listUsers.md
> +| --------- | ----------- | ---- | -------- |
sure

2022-07-27 03:55 UTC, YiyunNi approved these changes

2022-07-28 00:39 UTC, merged